apiVersion: v1
kind: Pod
metadata: 
  name: project-01
  labels:
    app: project-01
spec:
  containers:
    - name: database
      image: mongo:latest
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: db-vol 
          mountPath: /data 
    - name: backend
      image: titas2003/project-code:v1.0
      ports: 
        - containerPort: 3000
      env:
        - name: PORT
          value: "3000"
        - name: MONGO_URL
          value: "mongodb://10.108.208.199:27017/project-01"
  volumes:
    - name: db-vol
      hostPath:
        path: /media/project-01/data
        type: DirectoryOrCreate